# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
u1 = User.create!(username: 'user1', password: 'password')
u2 = User.create!(username: 'user2', password: 'password')
u3 = User.create!(username: 'user3', password: 'password')
u4 = User.create!(username: 'user4', password: 'password')
u5 = User.create!(username: 'user5', password: 'password')
u6 = User.create!(username: 'user6', password: 'password')
u7 = User.create!(username: 'user7', password: 'password')
u8 = User.create!(username: 'user8', password: 'password')
u9 = User.create!(username: 'user9', password: 'password')
u10 = User.create!(username: 'user10', password: 'password')
u11 = User.create!(username: 'user11', password: 'password')
u12= User.create!(username: 'user12', password: 'password')
u13= User.create!(username: 'user13', password: 'password')
u14= User.create!(username: 'user14', password: 'password')
u15= User.create!(username: 'user15', password: 'password')

p1=Post.create(user_id: u1.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://m.media-amazon.com/images/M/MV5BMTY2ODQ3NjMyMl5BMl5BanBnXkFtZTcwODg0MTUzNA@@._V1_.jpg')
p2=Post.create(user_id: u2.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://static.wikia.nocookie.net/jamescameronsavatar/images/e/e5/Avatar_TWoW_Neytiri_Textless_Poster.jpg/revision/latest?cb=20221125232909')
p3=Post.create(user_id: u2.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://staticg.sportskeeda.com/editor/2022/11/a402f-16694231050443-1920.jpg')
p4=Post.create(user_id: u3.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://i.pinimg.com/originals/fa/56/85/fa5685f79cc76a868d1d52cbc561d6fd.png')
p5=Post.create(user_id: u1.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqmIAPf_KnI3yQJVBEmJRU45AyfogG437VNw&usqp=CAU')
p6=Post.create(user_id: u3.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXubulSEOLZ6H4GggsyUoDXFUP5nIoAxsmZNz7etHicAsAf0Qi6ZKzpxwDLvi4pqsVWf0&usqp=CAU')
p7=Post.create(user_id: u1.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTaydn4_dn1PAv2SfnXz3A7jBXSR_x0unaKQ&usqp=CAU')
p8=Post.create(user_id: u3.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://images3.alphacoders.com/905/thumb-1920-905410.jpg')
p9=Post.create(user_id: u1.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://m.media-amazon.com/images/M/MV5BMTY2ODQ3NjMyMl5BMl5BanBnXkFtZTcwODg0MTUzNA@@._V1_.jpg')
p10=Post.create(user_id: u2.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://static.wikia.nocookie.net/jamescameronsavatar/images/e/e5/Avatar_TWoW_Neytiri_Textless_Poster.jpg/revision/latest?cb=20221125232909')
p11=Post.create(user_id: u2.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://staticg.sportskeeda.com/editor/2022/11/a402f-16694231050443-1920.jpg')
p12=Post.create(user_id: u3.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://i.pinimg.com/originals/fa/56/85/fa5685f79cc76a868d1d52cbc561d6fd.png')
p13=Post.create(user_id: u1.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqmIAPf_KnI3yQJVBEmJRU45AyfogG437VNw&usqp=CAU')
p14=Post.create(user_id: u3.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXubulSEOLZ6H4GggsyUoDXFUP5nIoAxsmZNz7etHicAsAf0Qi6ZKzpxwDLvi4pqsVWf0&usqp=CAU')
p15=Post.create(user_id: u1.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTaydn4_dn1PAv2SfnXz3A7jBXSR_x0unaKQ&usqp=CAU')
p16=Post.create(user_id: u3.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://images3.alphacoders.com/905/thumb-1920-905410.jpg')
p17=Post.create(user_id: u4.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://m.media-amazon.com/images/M/MV5BMTY2ODQ3NjMyMl5BMl5BanBnXkFtZTcwODg0MTUzNA@@._V1_.jpg')
p18=Post.create(user_id: u5.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://static.wikia.nocookie.net/jamescameronsavatar/images/e/e5/Avatar_TWoW_Neytiri_Textless_Poster.jpg/revision/latest?cb=20221125232909')
p19=Post.create(user_id: u6.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://staticg.sportskeeda.com/editor/2022/11/a402f-16694231050443-1920.jpg')
p20=Post.create(user_id: u7.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://i.pinimg.com/originals/fa/56/85/fa5685f79cc76a868d1d52cbc561d6fd.png')
p21=Post.create(user_id: u8.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqmIAPf_KnI3yQJVBEmJRU45AyfogG437VNw&usqp=CAU')
p22=Post.create(user_id: u8.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXubulSEOLZ6H4GggsyUoDXFUP5nIoAxsmZNz7etHicAsAf0Qi6ZKzpxwDLvi4pqsVWf0&usqp=CAU')
p23=Post.create(user_id: u9.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTaydn4_dn1PAv2SfnXz3A7jBXSR_x0unaKQ&usqp=CAU')
p24=Post.create(user_id: u9.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://images3.alphacoders.com/905/thumb-1920-905410.jpg')
p25=Post.create(user_id: u10.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://m.media-amazon.com/images/M/MV5BMTY2ODQ3NjMyMl5BMl5BanBnXkFtZTcwODg0MTUzNA@@._V1_.jpg')
p26=Post.create(user_id: u12.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://static.wikia.nocookie.net/jamescameronsavatar/images/e/e5/Avatar_TWoW_Neytiri_Textless_Poster.jpg/revision/latest?cb=20221125232909')
p27=Post.create(user_id: u12.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://staticg.sportskeeda.com/editor/2022/11/a402f-16694231050443-1920.jpg')
p28=Post.create(user_id: u13.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://i.pinimg.com/originals/fa/56/85/fa5685f79cc76a868d1d52cbc561d6fd.png')
p29=Post.create(user_id: u11.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqmIAPf_KnI3yQJVBEmJRU45AyfogG437VNw&usqp=CAU')
p30=Post.create(user_id: u13.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXubulSEOLZ6H4GggsyUoDXFUP5nIoAxsmZNz7etHicAsAf0Qi6ZKzpxwDLvi4pqsVWf0&usqp=CAU')
p31=Post.create(user_id: u14.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTaydn4_dn1PAv2SfnXz3A7jBXSR_x0unaKQ&usqp=CAU')
p32=Post.create(user_id: u15.id,title:Faker::Lorem.characters(number: 10),content:Faker::Lorem.paragraph,image_url:'https://images3.alphacoders.com/905/thumb-1920-905410.jpg')

pp p1.user_id